/** @type {import('../game-registry.js').GameConfig} */
export default {
  id: 'sexy-fruits',
  name: 'Sexy Fruits',
  gameCode: 'LGS-008',
  grid: { rows: 5, cols: 5 },
  emptySymbolId: 10,
  scatterSymbolId: 9,
  wildSymbolId: 0,
  symbols: {
    0: 'WILD',
    1: 'WMELON H1',
    2: 'GRAPES H2',
    3: 'BANANA H3',
    4: 'CHERRY H4',
    5: 'ACE A',
    6: 'KING K',
    7: 'QUEEN Q',
    8: 'JACK J',
    9: 'SCATTER',
    10: 'EMPTY',
  },
  emojis: {
    0: '🔥',
    1: '🍉',
    2: '🍇',
    3: '🍌',
    4: '🍒',
    5: 'A',
    6: 'K',
    7: 'Q',
    8: 'J',
    9: '⭐',
    10: '◌',
  },
  colors: {
    0: '#ff9800',
    1: '#ff5252',
    2: '#7e57c2',
    3: '#fbc02d',
    4: '#e91e63',
    5: '#26c6da',
    6: '#ff8f00',
    7: '#66bb6a',
    8: '#bdbdbd',
    9: '#ffeb3b',
    10: '#444',
  },
  defaultRequestBody: {
    betAmount: 20,
    cashBet: '20',
    choice: 1,
    currencyDec: 2,
    stakes: [{ type: 'commonGame' }],
    rtpOption: 'RTP_97',
  },
  playerId: 'QARealGameOperator:QARealGameBrand:jonas0n',
};
