/** @type {import('../game-registry.js').GameConfig} */
export default {
  id: 'sexy-fruits',
  name: 'Sexy Fruits',
  gameCode: 'LGS-008',
  grid: { rows: 5, cols: 5 },
  emptySymbolId: 10,
  scatterSymbolId: 8,
  wildSymbolId: 9,
  symbols: {
    0: 'WMELON H1',
    1: 'GRAPES H2',
    2: 'BANANA H3',
    3: 'CHERRY H4',
    4: 'ACE A',
    5: 'KING K',
    6: 'QUEEN Q',
    7: 'JACK J',
    8: 'SCATTER',
    9: 'WILD',
    10: 'EMPTY',
  },
  emojis: {
    0: '🍉',
    1: '🍇',
    2: '🍌',
    3: '🍒',
    4: 'A',
    5: 'K',
    6: 'Q',
    7: 'J',
    8: '⭐',
    9: '🔥',
    10: '◌',
  },
  colors: {
    0: '#ff5252',
    1: '#7e57c2',
    2: '#fbc02d',
    3: '#e91e63',
    4: '#26c6da',
    5: '#ff8f00',
    6: '#66bb6a',
    7: '#bdbdbd',
    8: '#ffeb3b',
    9: '#ff9800',
    10: '#444',
  },
  defaultRequestBody: {
    betAmount: 20,
    cashBet: '20',
    choice: 1,
    currencyDec: 2,
    stakes: [{ type: 'commonGame' }],
    rtpOption: 'RTP_97',
  },
  playerId: 'QARealGameOperator:QARealGameBrand:jonas0n',
};
